# Generated by Django 4.1.5 on 2023-02-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('parmanent_address', models.CharField(max_length=100)),
                ('nid', models.IntegerField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat')),
            ],
        ),
    ]
