# Generated by Django 4.1.5 on 2023-02-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
